GET http://127.0.0.1:8080/

<> 2023-08-08T171542.200.json
<> 2023-08-08T160600.200.json

###

POST http://127.0.0.1:8080/
Content-Type: application/json

{
    "lineItems": [
        {
            "productId": "98550cb7-8663-4418-92e7-b90eca55b18e",
            "quantity": "1"
        }
    ]
}

<> 2023-08-08T163328.200.json
<> 2023-08-08T162502.500.json
<> 2023-08-08T162158.500.json
<> 2023-08-08T162138.500.json
<> 2023-08-08T162056.400.json
<> 2023-08-08T162042.400.json
<> 2023-08-08T162002.500.json
<> 2023-08-08T161949.415.json
<> 2023-08-08T161938.400.html

###

POST http://127.0.0.1:8080/products/
Content-Type: application/json

{
    "name": "prod1",
    "stock": 1000
}

<> 2023-08-08T163316.200.json


###

DELETE http://127.0.0.1:8080/
Content-Type: application/json

{
    "lineItems": [
        {
            "productId": "98550cb7-8663-4418-92e7-b90eca55b18e",
            "quantity": "1"
        }
    ]
}

<> 2023-08-08T163353.200.json

####

POST http://127.0.0.1:8081/
Content-Type: application/json

{
    "lineItems": [
        {
            "productId": "9bf78485-2f1c-4466-9f49-174e8ae140b9",
            "quantity": "2"
        }
    ]
}

<> 2023-08-08T171612.500.json

###

GET http://127.0.0.1:8081/


###

POST http://127.0.0.1:8082/products/
Content-Type: application/json

{
    "name": "prod2-q",
    "stock": 300
}

####

GET http://127.0.0.1:8082/
Accept: application/json


###

POST http://127.0.0.1:8082/
Content-Type: application/json

{
    "lineItems": [
        {
            "productId": "9bf78485-2f1c-4466-9f49-174e8ae140b9",
            "quantity": "2"
        }
    ]
}


###

POST http://127.0.0.1:8082/products/
Content-Type: application/json

{
    "name": "prod333",
    "stock": 4340
}

###

POST http://127.0.0.1:8080/
Content-Type: application/json

{
    "lineItems": [
        {
            "productId": "98550cb7-8663-4418-92e7-b90eca55b18e",
            "quantity": "1"
        }
    ]
}


###

POST http://sales-app.k8s.local/inventory/products/
Content-Type: application/json

{
    "name": "prod2",
    "stock": 2000
}

###

GET http://sales-app.k8s.local/inventory/


###

POST http://sales-app.k8s.local/inventory/
Content-Type: application/json

{
    "lineItems": [
        {
            "productId": "d5de76de-9cef-44c2-bfab-18eebcb988ce",
            "quantity": "1"
        }
    ]
}

###

DELETE http://sales-app.k8s.local/inventory/
Content-Type: application/json

{
    "lineItems": [
        {
            "productId": "d5de76de-9cef-44c2-bfab-18eebcb988ce",
            "quantity": "1"
        }
    ]
}

###

POST https://sales-app.k8s.local/order/
Content-Type: application/json

{
    "lineItems": [
        {
            "productId": "d5de76de-9cef-44c2-bfab-18eebcb988ce",
            "quantity": "11"
        }
    ]
}

###

GET http://sales-app.k8s.local/inventoryqs/
Content-Type: application/json
Accept: application/json