inventory-svc:
  replicaCount: 1
  image:
    tag: "0.0.8-SNAPSHOT"

order-svc:
  replicaCount: 1
  image:
    tag: "0.0.3-SNAPSHOT"

inventoryqs-svc:
  replicaCount: 1
  image:
    tag: "0.0.8-SNAPSHOT"